name: Publish on npm registry

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'AxaFrance'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - run: npm ci
      - run: npm run build
      - run: npm --no-git-tag-version version "${{ steps.gitversion.outputs.fullSemVer }}"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
